"""Add has_accepted_terms to users

Revision ID: a230a4ea63cc
Revises: 6d5deb3c2e48
Create Date: 2025-08-06 14:45:22.731852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a230a4ea63cc'
down_revision: Union[str, Sequence[str], None] = '6d5deb3c2e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_accepted_terms', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_accepted_terms')
    # ### end Alembic commands ###
